# Dependencias
FROM node:22-alpine as deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm config set fetch-retry-maxtimeout 600000 && \
    npm config set fetch-retry-mintimeout 100000 && \
    npm install




# Builder - Construye la aplicación
FROM node:22-alpine as build

WORKDIR /usr/src/app

# Copiar de deps, los módulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# Copiar todo el codigo fuente de la aplicación
COPY . .

# RUN npm run test
RUN npm run build

RUN npm prune --omit=dev && npm cache clean --force

# Crear la imagen final de Docker
FROM node:22-alpine as prod

WORKDIR /usr/src/app

RUN apk add --no-cache libc6-compat

COPY --from=build --chown=node:node /usr/src/app/node_modules ./node_modules

# Copiar la carpeta de DIST
COPY --from=build --chown=node:node /usr/src/app/dist ./dist


ENV NODE_ENV=production

USER node


EXPOSE 3000

CMD [ "node", "dist/main.js" ]